spring:
  profiles:
    active: docker

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/calculadora}
    username: ${SPRING_DATASOURCE_USERNAME:challenger}
    password: ${SPRING_DATASOURCE_PASSWORD:prueba}
    driver-class-name: org.postgresql.Driver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 10
      idle-timeout: 30000
      connection-timeout: 30000
      max-lifetime: 60000

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        use_sql_comments: true
    show-sql: true

  application:
    name: backend-challenger-api

  springfox:
    documentation:
      enabled: true
